# Generated by Django 2.2.12 on 2020-06-01 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0003_auto_20200531_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='location',
            field=models.CharField(default='Neverland', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
